### ISSUE TITLE
HTMLElement.rootElement is deprecated.

### ISSUE THREAD

**Issue by kerabromsmu** [nick-f/an-old-hope-light-syntax-atom#1]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `rootElement` and access
the editor contents directly instead.
```
HTMLElement.rootElement (F:\Users\Dimage\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:23:10)
getFromShadowDom (C:\Users\Dimage\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:16:19)
attach (C:\Users\Dimage\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:26:22)
<unknown> (C:\Users\Dimage\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:125:13)
Workspace.observeTextEditors (<embedded>:26602:15)
ToolTipProvider.activate (C:\Users\Dimage\.atom\packages\ide-purescript\node_modules\hover-tooltips\lib\hover-tooltips.js:122:43)
```

**Comment by nick-f** [comment]
Hi there, sorry for the tardy response.

I'm running the theme in the latest version of Atom (currently 1.23.3) on macOS and do not see any complaints from the editor about that. Also a search of the repo doesn't show any results for `rootElement`.

Happy to fix it if you can point out where it's being used.

**Comment by nick-f** [comment]
Unable to replicate. Please feel free to re-open the issue if you find this is still occurring or there are replication steps.
